### ISSUE TITLE
sed error: invalid reference \1 on `s' command's RHS

### ISSUE THREAD

**Issue by dark-saber** [E5ten/pacaur#15]
The latest version (cd9c9f40aba1c6d2ced89b8aca8f0d0313512e5d) doesn't build for me in Arch Linux:
```
==> Starting package()...
make: Entering directory '/mnt/WD4e/makepkg/pacaur-git/src/pacaur'
Generating documentation...
Installing...
sed: -e expression #1, char 50: invalid reference \1 on `s' command's RHS
make: *** [Makefile:54: install] Error 1
make: Leaving directory '/mnt/WD4e/makepkg/pacaur-git/src/pacaur'
```

**Comment by E5ten** [comment]
Sorry about that, it should be fixed now. I'm not sure why, but GNU sed doesn't seem to enable extended regex for commands before specified after the `-E` flag, which I don't think makes sense given that the flag is supposed to enable extended regex for the whole command/script. Either way I believe it works now.
