### ISSUE TITLE
Output of `pacaur --help` is incorrect

### ISSUE THREAD

**Issue by zman0900** [E5ten/pacaur#19]
###### Version

`pacaur -v`

```
pacaur 4.8.6
```

###### Description

`pacaur --help` shows the following for AUR specific commands:

```
 AUR specific
   sync             clone, build and install target(s)
   search           search AUR for matching strings
   info             view package information
   buildonly        clone and build target(s)
   upgrade          upgrade AUR package(s)
   check            check for AUR upgrade(s)
   clean            clean AUR package(s) and clone(s)
   cleanall         clean all AUR packages and clones
```

But actually running one of these commands no longer works with the 4.8 version of pacaur:

Output of `pacaur check` :

```
error: no operation specified (use -h for help)
```

According to the man page, all these commands must be prefixed with `--aur-`.  Help text and any corresponding bash completion should be updated to match the man page.

**Comment by E5ten** [comment]
Fixed in master (these subcommands/--aur-* flags are removed in favour of obtaining the same functionality by using the -a or --aur flag in combination with the normal flags)
