### ISSUE TITLE
Overwite flag not working

### ISSUE THREAD

**Issue by jadic27** [E5ten/pacaur#21]
OS : ARCH
DE : KDE
PACAUR VERSION :  4.8.6

pacaur -Syyuu --overwrite

python-pip: /usr/lib/python3.8/site-packages/pip/_internal/utils/__pycache__/inject_securetransport.cpython-38.pyc exists in filesystem
python-pip: /usr/lib/python3.8/site-packages/pip/_internal/utils/__pycache__/subprocess.cpython-38.pyc exists in filesystem
python-pip: /usr/lib/python3.8/site-packages/pip/_internal/utils/__pycache__/unpacking.cpython-38.pyc exists in filesystem
python-pip: /usr/lib/python3.8/site-packages/pip/_internal/utils/__pycache__/urls.cpython-38.pyc exists in filesystem
python-pip: /usr/lib/python3.8/site-packages/pip/_internal/utils/filetypes.py exists in filesystem
python-pip: /usr/lib/python3.8/site-packages/pip/_internal/utils/inject_securetransport.py exists in filesystem
python-pip: /usr/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py exists in filesystem
python-pip: /usr/lib/python3.8/site-packages/pip/_internal/utils/unpacking.py exists in filesystem
python-pip: /usr/lib/python3.8/site-packages/pip/_internal/utils/urls.py exists in filesystem

`--overwrite flag not working`

**Comment by E5ten** [comment]
--overwrite requires an argument, if you want to overwrite anything that might be in conflict you would use the argument '*'. The fact that it didn't error due to the missing argument is an issue, but that is fixed in master.

**Comment by jadic27** [comment]
thanks
